import type { RoadmapNode } from "./types";

/** 演进路线：里程碑 + 代表论文（短标签用于大图展示，悬停见全称） */
export const roadmapNodes: RoadmapNode[] = [
  {
    id: "mf",
    year: 2009,
    label: "矩阵分解 / 协同过滤成熟期",
    shortLabel: "矩阵分解时代",
    type: "milestone",
    era: "判别式主范式",
    description:
      "隐语义、FM、Wide&Deep 等形成工业级「召回–粗排–精排」基座；以点积/MLP 判别为主。",
  },
  {
    id: "gru4rec",
    year: 2015,
    month: 9,
    label: "GRU4Rec",
    type: "paper",
    era: "序列生成萌芽",
    paperTitle: "Session-based Recommendations with Recurrent Neural Networks",
    paperUrl: "https://arxiv.org/abs/1511.06939",
    description: "将会话建模为序列，用 RNN 预测下一物品，为「下一项生成」打基础。",
  },
  {
    id: "sasrec",
    year: 2018,
    month: 8,
    label: "SASRec",
    type: "paper",
    era: "Transformer 序列",
    paperTitle: "Self-Attentive Sequential Recommendation",
    paperUrl: "https://arxiv.org/abs/1808.09781",
    description: "自注意力序列骨干，工业界大量作为行为编码器。",
  },
  {
    id: "bert4rec",
    year: 2019,
    month: 4,
    label: "BERT4Rec",
    type: "paper",
    era: "双向序列预训练",
    paperTitle:
      "BERT4Rec: Sequential Recommendation with Bidirectional Encoder Representations from Transformer",
    paperUrl: "https://arxiv.org/abs/1904.06690",
    description: "MLM 式序列去噪；线上需对齐因果 Serving。",
  },
  {
    id: "vae-gan-cf",
    year: 2020,
    label: "VAE/GAN 生成式协同过滤探索",
    shortLabel: "VAE/GAN CF",
    type: "milestone",
    era: "生成式补丁期",
    description:
      "VAECF、IRGAN 等用生成模型补数据稀疏；多生成隐向量而非直接生成候选列表。",
  },
  {
    id: "p5",
    year: 2022,
    month: 3,
    label: "P5（Recommendation as Language Processing）",
    shortLabel: "P5",
    type: "paper",
    era: "LLM4Rec 探索",
    paperTitle:
      "Recommendation as Language Processing (RLP): A Unified Pretrain, Personalized Prompt & Predict Paradigm (P5)",
    paperUrl: "https://arxiv.org/abs/2203.13366",
    description: "多任务模板化，验证「文本化推荐」路线；推理成本与词表问题是瓶颈。",
  },
  {
    id: "llm4rec-era",
    year: 2022,
    month: 11,
    label: "LLM4Rec 三大范式成形",
    shortLabel: "LLM4Rec 范式",
    type: "milestone",
    era: "Embeddings / Tokens / LLM-as-RS",
    description:
      "LLM 作特征、作标签 Token、或直接当 RS 三条路径并行探索；明确端到端成本与词表瓶颈。",
  },
  {
    id: "tiger",
    year: 2023,
    month: 5,
    label: "TIGER：语义 ID + 生成式检索（Google）",
    shortLabel: "TIGER",
    type: "paper",
    era: "生成式检索爆发",
    paperTitle: "Recommender Systems with Generative Retrieval (TIGER)",
    paperUrl: "https://arxiv.org/abs/2305.05065",
    description:
      "RQ-VAE 语义 ID + 自回归解码候选；把「检索」改写为生成离散码本序列，适配亿级目录。",
  },
  {
    id: "hstu",
    year: 2024,
    month: 2,
    label: "HSTU / Generative Recommenders（Meta）",
    shortLabel: "HSTU",
    type: "paper",
    era: "生成式精排 + Scaling Law",
    paperTitle: "Actions Speak Louder than Words: Trillion-Parameter Sequential Transducers for Generative Recommendations",
    paperUrl: "https://arxiv.org/abs/2402.17152",
    description:
      "面向高基数流式数据的 HSTU；公开大规模实验与线上 A/B，验证算力缩放与延迟优化（相对 FlashAttention2）。",
  },
  {
    id: "onerec",
    year: 2025,
    month: 6,
    label: "OneRec：端到端生成式推荐（快手）",
    shortLabel: "OneRec",
    type: "paper",
    era: "召排一体落地",
    paperTitle: "OneRec: Towards End-to-End Generative Recommendation",
    paperUrl: "https://arxiv.org/abs/2506.13695",
    description:
      "Encoder–Decoder 自回归 Top-K；偏好对齐与工程优化支撑主站大规模流量（公开技术报告数据以论文为准）。",
  },
  {
    id: "rankmixer",
    year: 2025,
    month: 7,
    label: "RankMixer：工业排序模型规模化（字节）",
    shortLabel: "RankMixer",
    type: "paper",
    era: "大排序模型工程化",
    paperTitle: "RankMixer: Scaling Up Ranking Models in Industrial Recommenders",
    paperUrl: "https://arxiv.org/abs/2507.15551",
    description:
      "Token mixing + 稀疏 MoE，面向严格延迟/吞吐；论文报告 MFU 与线上时长类指标提升（见原文）。",
  },
  {
    id: "onetrans",
    year: 2025,
    month: 10,
    label: "OneTrans：序列 + 特征交互统一 Transformer（工业）",
    shortLabel: "OneTrans",
    type: "paper",
    era: "统一骨干",
    paperTitle: "OneTrans: Unified Feature Interaction and Sequence Modeling with One Transformer in Industrial Recommender",
    paperUrl: "https://arxiv.org/abs/2510.26104",
    description:
      "将行为序列与非序列特征 token 化进同一 Transformer；因果注意力 + 跨请求 KV 缓存，论文报告 GMV 类线上收益。",
  },
  {
    id: "hybrid-era",
    year: 2025,
    month: 6,
    label: "混合架构与电商/广告深化（行业）",
    shortLabel: "混合架构深化",
    type: "milestone",
    era: "成本与稳定性优先",
    description:
      "LUM / HLLM / GenRank 等「生成式增强级联」与 OneMall、GR4AD 等垂直场景方案并行；Lazy Decoder、蒸馏、MoE 降本。",
  },
];
